#ifndef COMMON_H
#define COMMON_H



#define CONS_ATTEMPTS_COUNT 5

#define CONST_VANS 13
#define CONST_VAN_RIDE_BOX_PROBABILITY 0.695
#define CONST_VAN_RIDE_NOBOX_MIN 452
#define CONST_VAN_RIDE_NOBOX_MAX 537
#define CONST_VAN_RIDE_BOX_MIN 447
#define CONST_VAN_RIDE_BOX_MAX 532
#define CONST_VAN_RETURN_RIDE_TIME_MIN 10
#define CONST_VAN_RETURN_RIDE_TIME_MAX 15
#define CONST_VAN_CANCELED_RIDE_TIME_MIN 15
#define CONST_VAN_CANCELED_RIDE_TIME_MAX 45

#define CONST_VANS_SHIFT_LENGTH (8.0 * 60.0)
#define CONST_VAN_CAPACITY 157
#define CONST_VAN_LOAD_TIME_MIN 74
#define CONST_VAN_LOAD_TIME_MAX 84


#define CONST_EMPLOYEES 26
#define CONST_EMPLOYEE_PACKET_LOAD_TIME 0.30
#define CONST_EMPLOYEE_PACKET_UNLOAD_TIME 0.45


#define CONST_TRUCKS 4
#define CONST_TRUCK_CAPACITY (CONST_VAN_CAPACITY*6)
#define CONST_TRUCK_TRAVEL_TIME_MIN 45
#define CONST_TRUCK_TRAVEL_TIME_MAX 480
#define CONST_TRUCK_WORK_ON_WAY_TIME_MIN 0
#define CONST_TRUCK_WORK_ON_WAY_TIME_MAX 562
#define CONST_TRUCK_UNLOAD_TIME_MIN 107
#define CONST_TRUCK_UNLOAD_TIME_MAX 117



#define CONST_WORKING_SHIFT_LENGTH (24*60)



#endif
